### ISSUE TITLE
Autocomplete items

### ISSUE THREAD

**Issue by monymirza** [eugenegantz/MSelectDialogBox#1]
Is there any option to choose that if i start type in field and autocomplete result should filter result "start with" instead contains.

**Comment by eugenegantz** [comment]
You can use custom autocomplete filter
Example:

```
var customFilter = function(inputString, optionString){
    var pattern = new RegExp("^" + inputString.trim(),"ig");
    optionString = String(optionString);
    return Boolean(optionString.match(pattern));
};

$("#selector").mSelectDBox({
    "list": [
        "aa-bb-cc-dd-1",
        "bb-cc-dd-aa-2",
        "cc-dd-aa-bb-3",
        "dd-aa-bb-cc-4"
    ],
    "optionFilters": [customFilter],
    "multiple": false,
    "autoComplete": true
});
```

[demo](http://eugenegantz.ru/demo/MSelectDBox/example2.html)

**Comment by monymirza** [comment]
Any possibilty if "multiple": true
`"multiple": true,`

**Comment by eugenegantz** [comment]
In this case it does not matter
it can be used also with `"multiple": true`
[demo](http://eugenegantz.ru/demo/MSelectDBox/example2.html)

**Comment by monymirza** [comment]
Thanks, it works...
