### ISSUE TITLE
Max select items

### ISSUE THREAD

**Issue by monymirza** [eugenegantz/MSelectDialogBox#2]
Hi,

Is there any option that we can select max items in `multiple` list ? for eaxmple, i have a list of 10 items and only want user to max select 4 options.

**Comment by eugenegantz** [comment]
For now there is no native support of this feature.
But you can do some workaround by using events
Example:

```
var onSelect = function(self){
    var values = self.getSelectedValues();
    if (values.length > 4){
        values.pop();
        self.select({value: values});
        alert("Only <= 4");
    }
};

$("#msdb-c").mSelectDBox({
    "list": ["1", "2", "3", "4", "5", "6", "7"],
    "multiple": true,
    "autoComplete": true,
    "onselect": onSelect
});
```

[Demo](http://eugenegantz.ru/demo/MSelectDBox/example2.html)

**Comment by monymirza** [comment]
Thanks,
