### ISSUE TITLE
Backspace clear input

### ISSUE THREAD

**Issue by monymirza** [eugenegantz/MSelectDialogBox#3]
As per demo https://eugenegantz.github.io/MSelectDialogBox/example.html
2nd example ( multiple = true, autoComplete = true )

I type "am" and get filtered result, then i press Backspace 1 time, it clears whole field while it should only remove last letter "m" and remain filtered results with "a".

**Comment by eugenegantz** [comment]
Thank you for your attention.
I suppose it was fixed in last commit.
[demo](https://eugenegantz.github.io/MSelectDialogBox/examples/example-1.html)
