### ISSUE TITLE
Падение при вызове val()

### ISSUE THREAD

**Issue by enz0jke** [eugenegantz/MSelectDialogBox#4]
при вызове функции val() для элементов не содержащих аттрибута data-msdb-value
js падает с ошибкой:
`Uncaught TypeError: Cannot read property 'toLowerCase' of undefined`

вероятно причина в [этом](https://github.com/eugenegantz/MSelectDialogBox/blob/master/dist/m-select-d-box.js#L2486)
потому как валидный вызов:
`jQueryValFn.apply(this, arguments);`
[пруф](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply)

**Comment by eugenegantz** [comment]
Добрый день. 
Да это мои бока. 
Спасибо за внимательность, надеюсь, что решил проблему в последнем коммите.

**Comment by enz0jke** [comment]
угумс, спасибо за оперативные правки =)
